import { describe, it, expect } from '@jest/globals';
import { ChameleonAesGcm } from '../src/crypto/chameleon-aes-gcm.js';

describe('ChameleonAesGcm', () => {
  describe('cross-language compatibility', () => {
    // Fixture produced by chameleon-data-pipelines' own real code path
    // (app/core/crypto.py's ChameleonCrypto.encrypt, packaged the exact
    // way pii_vault_sync.py's _encrypt_field does: key_id:iv_b64:ciphertext_b64,
    // iv/ciphertext base64-encoded separately) -- not re-derived or
    // hand-rolled, generated by actually running the Python code and
    // copying its real output. If this ever stops decrypting, the two
    // implementations have drifted apart for real.
    const dekHex = 'a3155cde1ca95aadd7ec1c03b75bcde1ed882bbc2288c0afae08f574c67e1049';
    const userId = 'user_verify_12345';
    const plaintext = 'verify-roundtrip@example.com';
    const ivB64 = 'yTUdvEqhzpvLXMA1';
    const ciphertextB64 = 'mbB/UPJHhP7IhDz49zwZ5NOqxTvNwy4qI5eihriPfKmLeRPThn86UkHmqu0=';

    it('decrypts a real ciphertext produced by the Python ChameleonCrypto/pii_vault_sync path', () => {
      const dek = Buffer.from(dekHex, 'hex');
      const result = ChameleonAesGcm.decrypt(ivB64, ciphertextB64, userId, dek);
      expect(result).toBe(plaintext);
    });
  });

  describe('round trip', () => {
    const userId = 'user123';
    const plaintext = 'jane.doe@example.com';

    it('encrypts and decrypts back to the original plaintext', () => {
      const dek = Buffer.from('00'.repeat(32), 'hex');
      const { ivB64, ciphertextB64 } = ChameleonAesGcm.encrypt(plaintext, userId, dek);
      const result = ChameleonAesGcm.decrypt(ivB64, ciphertextB64, userId, dek);
      expect(result).toBe(plaintext);
    });

    it('produces a different IV (and ciphertext) on every call -- randomized, not deterministic', () => {
      const dek = Buffer.from('11'.repeat(32), 'hex');
      const a = ChameleonAesGcm.encrypt(plaintext, userId, dek);
      const b = ChameleonAesGcm.encrypt(plaintext, userId, dek);
      expect(a.ivB64).not.toBe(b.ivB64);
      expect(a.ciphertextB64).not.toBe(b.ciphertextB64);
    });

    it('fails to decrypt when the AAD (userId) does not match', () => {
      const dek = Buffer.from('22'.repeat(32), 'hex');
      const { ivB64, ciphertextB64 } = ChameleonAesGcm.encrypt(plaintext, userId, dek);
      expect(() => ChameleonAesGcm.decrypt(ivB64, ciphertextB64, 'someone-else', dek)).toThrow();
    });

    it('fails to decrypt with the wrong key', () => {
      const dek = Buffer.from('33'.repeat(32), 'hex');
      const wrongDek = Buffer.from('44'.repeat(32), 'hex');
      const { ivB64, ciphertextB64 } = ChameleonAesGcm.encrypt(plaintext, userId, dek);
      expect(() => ChameleonAesGcm.decrypt(ivB64, ciphertextB64, userId, wrongDek)).toThrow();
    });

    it('rejects a DEK that is not 32 bytes', () => {
      const shortDek = Buffer.from('00'.repeat(16), 'hex');
      expect(() => ChameleonAesGcm.encrypt(plaintext, userId, shortDek)).toThrow();
      expect(() => ChameleonAesGcm.decrypt('AAAAAAAAAAAAAAAAAAAA', 'AAAA', userId, shortDek)).toThrow();
    });
  });
});
