import { BigQuery } from '@google-cloud/bigquery';
import { createLogger } from '../logging/index.js';
import type {
  DeletionStrategy,
  GhostDataScanPolicy,
  PiiFieldPolicy,
  PiiRegistryEntry,
  PiiResourceLayer,
  PiiResourceVisibility,
  PiiSystem,
} from '../types/pii-registry.js';

const logger = createLogger('pii-registry-repository');

export interface RegistryRow {
  resource_id: string;
  model_name: string;
  system: string;
  resource_layer: string;
  owner: string;
  field_name: string;
  classification: string;
  handling: string;
  confidence: string;
  detection_method: string;
  required_in_mart: boolean;
  registry_version: string;
}

export interface LineageRow {
  source_resource_id: string;
  field_name: string;
  downstream_model: string;
  hops: number;
}

function toEntry(resourceId: string, rows: RegistryRow[], lineage: LineageRow[]): PiiRegistryEntry {
  const first = rows[0];
  const layer = (first.resource_layer || 'UNKNOWN') as PiiResourceLayer;
  const isRaw = layer === 'RAW';
  const isSaas = layer === 'SAAS';
  const isMart = layer === 'MART';

  const piiFields: PiiFieldPolicy[] = rows.map((row) => ({
    name: row.field_name,
    classification: row.classification as PiiFieldPolicy['classification'],
    handling: row.handling as PiiFieldPolicy['handling'],
    requiredInMart: Boolean(row.required_in_mart),
    confidence: row.confidence as PiiFieldPolicy['confidence'],
    evidence: [`dbt:detection:${row.detection_method}`],
  }));

  const visibility: PiiResourceVisibility = isRaw ? 'INTERNAL' : 'CUSTOMER_FACING';
  const deletionStrategy: DeletionStrategy = isMart ? 'MANUAL_REVIEW' : 'CRYPTO_SHRED';
  const ghostDataScan: GhostDataScanPolicy =
    isRaw || isSaas
      ? { enabled: false, scanMode: 'DISABLED', patterns: [] }
      : { enabled: true, scanMode: 'SAMPLED', patterns: ['EMAIL', 'PHONE', 'NAME'] };

  const evidencePointers = [
    `dbt:model:${first.model_name}`,
    ...lineage.map((edge) => `lineage:used_in=${edge.downstream_model}:${edge.field_name}@${edge.hops}hops`),
  ];

  return {
    registryVersion: first.registry_version,
    resourceId,
    system: (first.system as PiiSystem) ?? 'bigquery',
    resourceLayer: layer,
    visibility,
    tenantIdColumn: 'tenant_id',
    userIdColumn: 'user_id',
    piiFields,
    ownerConnector: first.owner || 'dbt',
    lineageDestination: resourceId,
    deletionStrategy,
    ghostDataScan,
    handlingPolicy: `${layer.toLowerCase()}_auto_registry`,
    evidencePointers,
    notes: 'Generated by the chameleon_pii dbt package from warehouse metadata.',
  };
}

/**
 * Pure mapping from the flat dbt rows to grouped PiiRegistryEntry objects. No I/O —
 * this is the unit-tested core. Resource-level policy knobs the dbt layer does not
 * yet declare (deletion strategy, scan policy, tenant/user scoping) are derived here
 * with conservative defaults; they can later be declared in dbt via model
 * `meta.chameleon` and read through verbatim instead of derived.
 */
export function assemblePiiRegistryEntries(
  registryRows: RegistryRow[],
  lineageRows: LineageRow[]
): PiiRegistryEntry[] {
  if (registryRows.length === 0) {
    return [];
  }

  const byResource = new Map<string, RegistryRow[]>();
  for (const row of registryRows) {
    const existing = byResource.get(row.resource_id);
    if (existing) {
      existing.push(row);
    } else {
      byResource.set(row.resource_id, [row]);
    }
  }

  const lineageByResource = new Map<string, LineageRow[]>();
  for (const edge of lineageRows) {
    const existing = lineageByResource.get(edge.source_resource_id);
    if (existing) {
      existing.push(edge);
    } else {
      lineageByResource.set(edge.source_resource_id, [edge]);
    }
  }

  const entries: PiiRegistryEntry[] = [];
  for (const [resourceId, rows] of byResource) {
    entries.push(toEntry(resourceId, rows, lineageByResource.get(resourceId) ?? []));
  }
  return entries;
}

/**
 * Federates the registry by source. The dbt package is authoritative ONLY for the
 * resources it manages (ownerConnector === 'dbt': staging/intermediate/mart models);
 * every other source — raw ingestion, SaaS connectors (HubSpot, Salesforce), platform
 * events — is supplied by `connectorEntries` and must be preserved untouched.
 *
 * User-declared ("manual") entries are a third, tenant-scoped slice layered on top:
 * they are never overwritten by the connector/dbt slices, and because they carry a
 * tenantId they coexist with same-resourceId platform entries. They are appended last
 * so a manual declaration wins for its own (tenant, resourceId).
 *
 * If the dbt slice is empty (tables not built / unreachable), the connector registry
 * is used unchanged (plus any manual entries).
 */
export function composePiiRegistry(
  connectorEntries: PiiRegistryEntry[],
  dbtEntries: PiiRegistryEntry[],
  manualEntries: PiiRegistryEntry[] = []
): PiiRegistryEntry[] {
  if (dbtEntries.length === 0 && manualEntries.length === 0) {
    return connectorEntries;
  }
  const platform =
    dbtEntries.length === 0
      ? connectorEntries
      : [...connectorEntries.filter((entry) => entry.ownerConnector !== 'dbt'), ...dbtEntries];
  return manualEntries.length === 0 ? platform : [...platform, ...manualEntries];
}

/**
 * Loads the PII registry from the tables produced by the `chameleon_pii` dbt
 * package (`pii_registry` + `pii_field_lineage`), regardless of which
 * warehouse dbt built them into.
 */
export interface IPiiRegistryRepository {
  loadEntries(): Promise<PiiRegistryEntry[]>;
}

/**
 * Loads the PII registry from the tables produced by the `chameleon_pii` dbt
 * package (`pii_registry` + `pii_field_lineage`) and assembles them into the
 * PiiRegistryEntry shape the Key Vault serves.
 */
export class BigQueryPiiRegistryRepository implements IPiiRegistryRepository {
  private bq: BigQuery;

  constructor(
    private readonly projectId: string,
    private readonly datasetId: string
  ) {
    this.bq = new BigQuery({ projectId });
  }

  async loadEntries(): Promise<PiiRegistryEntry[]> {
    const [registryRows, lineageRows] = await Promise.all([this.queryRegistry(), this.queryLineage()]);
    const entries = assemblePiiRegistryEntries(registryRows, lineageRows);

    if (entries.length > 0) {
      logger.info(
        { resourceCount: entries.length, fieldCount: registryRows.length },
        'Loaded PII registry from dbt-produced BigQuery tables'
      );
    }
    return entries;
  }

  private async queryRegistry(): Promise<RegistryRow[]> {
    const query = `SELECT
        resource_id, model_name, system, resource_layer, owner,
        field_name, classification, handling, confidence, detection_method,
        required_in_mart, registry_version
      FROM \`${this.projectId}.${this.datasetId}.pii_registry\``;
    const [rows] = await this.bq.query({ query });
    return rows as RegistryRow[];
  }

  private async queryLineage(): Promise<LineageRow[]> {
    try {
      const query = `SELECT source_resource_id, field_name, downstream_model, hops
        FROM \`${this.projectId}.${this.datasetId}.pii_field_lineage\``;
      const [rows] = await this.bq.query({ query });
      return rows as LineageRow[];
    } catch (error) {
      // Lineage is enrichment only — a missing table should not block the registry.
      logger.warn({ error }, 'pii_field_lineage unavailable; continuing without lineage evidence');
      return [];
    }
  }
}
